### PR TITLE
macOS awareness, electron3 necessary rebuild

### PR DESCRIPTION
**Pull request by Equanox**
@puengel can you check on windows?

It might be necessary to redo a `npm install`

### CODE REVIEW

**Comment by puengel** [comment]
Verified on Windows.

**Comment by margolisj** [comment]
@Equanox Is there any more work to be done here to merge these commits? I'm also interested in merging a few other changes I've made, if you're accepting merge requests.

**Comment by Equanox** [comment]
@margolisj can't test if it really works cause i have no access to a mac right now. Would be really helpful if someone can test it while considering the discussion in #9 .

I'll definitely accept pull requests. But it might be helpful to discuss the things you want to change in advance. Feel free to create a issue for your purpose.

FYI, @puengel is actually rewriting the go => nodejs/electronjs bridge in a separate repository. This will allow you to import gotron in your go project without the UI overhead, and enable you to change BrowserWindow parameters directly from go. The work should be ready to merge till end of the year.

**Comment by puengel** [comment]
See https://github.com/Equanox/gotron/issues/9#issuecomment-449418596

**Pull request closed without merging**
